<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerT4LJYyJ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerT4LJYyJ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerT4LJYyJ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerT4LJYyJ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerT4LJYyJ\App_KernelDevDebugContainer([
    'container.build_hash' => 'T4LJYyJ',
    'container.build_id' => 'e40ac3c2',
    'container.build_time' => 1582817447,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerT4LJYyJ');
